// <auto-generated />
// This file is auto-maintained by EF Core migrations.
// It records the current model so that future migrations can diff against it.
using System;
using CorporateMemo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorporateMemo.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // AspNetRoles
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                b.Property<string>("Name").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.HasKey("Id");
                b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex").HasFilter("[NormalizedName] IS NOT NULL");
                b.ToTable("AspNetRoles", (string)null);
            });

            // AspNetUsers (ApplicationUser)
            modelBuilder.Entity("CorporateMemo.Domain.Entities.ApplicationUser", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<int>("AccessFailedCount").HasColumnType("int");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                b.Property<string>("Department").HasColumnType("nvarchar(max)");
                b.Property<string>("DisplayName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<bool>("EmailConfirmed").HasColumnType("bit");
                b.Property<bool>("LockoutEnabled").HasColumnType("bit");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetimeoffset");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("PasswordHash").HasColumnType("nvarchar(max)");
                b.Property<string>("PhoneNumber").HasColumnType("nvarchar(max)");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("bit");
                b.Property<string>("SecurityStamp").HasColumnType("nvarchar(max)");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("bit");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.HasKey("Id");
                b.HasIndex("DisplayName").HasDatabaseName("IX_AspNetUsers_DisplayName");
                b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex").HasFilter("[NormalizedUserName] IS NOT NULL");
                b.ToTable("AspNetUsers", (string)null);
            });

            // Memos
            modelBuilder.Entity("CorporateMemo.Domain.Entities.Memo", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime?>("ApprovedDate").HasColumnType("datetime2");
                b.Property<string>("AuthorEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("AuthorId").IsRequired().HasMaxLength(450).HasColumnType("nvarchar(450)");
                b.Property<string>("AuthorName").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("CcRecipients").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Content").HasMaxLength(10000).HasColumnType("nvarchar(max)");
                b.Property<DateTime>("DateCreated").HasColumnType("datetime2");
                b.Property<bool>("IsConfidential").HasColumnType("bit");
                b.Property<string>("MemoNumber").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("Tags").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Title").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("ToRecipients").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("AuthorId").HasDatabaseName("IX_Memos_AuthorId");
                b.HasIndex("MemoNumber").IsUnique().HasDatabaseName("IX_Memos_MemoNumber");
                b.HasIndex("Status").HasDatabaseName("IX_Memos_Status");
                b.ToTable("Memos");
            });

            // ApprovalSteps
            modelBuilder.Entity("CorporateMemo.Domain.Entities.ApprovalStep", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("ApproverId").IsRequired().HasMaxLength(450).HasColumnType("nvarchar(450)");
                b.Property<string>("ApproverEmail").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("ApproverName").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("Comment").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<DateTime?>("DecidedAt").HasColumnType("datetime2");
                b.Property<int>("Decision").HasColumnType("int");
                b.Property<Guid>("MemoId").HasColumnType("uniqueidentifier");
                b.Property<int>("Order").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex(new[] { "ApproverId", "MemoId" }).HasDatabaseName("IX_ApprovalSteps_ApproverId_MemoId");
                b.HasIndex("MemoId").HasDatabaseName("IX_ApprovalSteps_MemoId");
                b.ToTable("ApprovalSteps");
            });

            // Attachments
            modelBuilder.Entity("CorporateMemo.Domain.Entities.Attachment", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("ContentType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("FileName").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<long>("FileSizeBytes").HasColumnType("bigint");
                b.Property<Guid>("MemoId").HasColumnType("uniqueidentifier");
                b.Property<string>("StoragePath").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTime>("UploadedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("MemoId");
                b.ToTable("Attachments");
            });

            // Notifications
            modelBuilder.Entity("CorporateMemo.Domain.Entities.Notification", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<bool>("IsRead").HasColumnType("bit");
                b.Property<string>("Message").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<Guid?>("MemoId").HasColumnType("uniqueidentifier");
                b.Property<int>("Type").HasColumnType("int");
                b.Property<string>("UserId").IsRequired().HasMaxLength(450).HasColumnType("nvarchar(450)");
                b.HasKey("Id");
                b.HasIndex(new[] { "UserId", "IsRead" }).HasDatabaseName("IX_Notifications_UserId_IsRead");
                b.ToTable("Notifications");
            });

            // Identity join/claims tables
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
                b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
                b.Property<string>("RoleId").IsRequired().HasColumnType("nvarchar(450)");
                b.HasKey("Id");
                b.HasIndex("RoleId").HasDatabaseName("IX_AspNetRoleClaims_RoleId");
                b.ToTable("AspNetRoleClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
                b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
                b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                b.HasKey("Id");
                b.HasIndex("UserId").HasDatabaseName("IX_AspNetUserClaims_UserId");
                b.ToTable("AspNetUserClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
                b.Property<string>("ProviderKey").HasColumnType("nvarchar(450)");
                b.Property<string>("ProviderDisplayName").HasColumnType("nvarchar(max)");
                b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                b.HasKey("LoginProvider", "ProviderKey");
                b.HasIndex("UserId").HasDatabaseName("IX_AspNetUserLogins_UserId");
                b.ToTable("AspNetUserLogins", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId").HasColumnType("nvarchar(450)");
                b.Property<string>("RoleId").HasColumnType("nvarchar(450)");
                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId").HasDatabaseName("IX_AspNetUserRoles_RoleId");
                b.ToTable("AspNetUserRoles", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId").HasColumnType("nvarchar(450)");
                b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
                b.Property<string>("Name").HasColumnType("nvarchar(450)");
                b.Property<string>("Value").HasColumnType("nvarchar(max)");
                b.HasKey("UserId", "LoginProvider", "Name");
                b.ToTable("AspNetUserTokens", (string)null);
            });

            // Configure relationships
            modelBuilder.Entity("CorporateMemo.Domain.Entities.ApprovalStep", b =>
            {
                b.HasOne("CorporateMemo.Domain.Entities.Memo", "Memo")
                    .WithMany("ApprovalSteps")
                    .HasForeignKey("MemoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Memo");
            });

            modelBuilder.Entity("CorporateMemo.Domain.Entities.Attachment", b =>
            {
                b.HasOne("CorporateMemo.Domain.Entities.Memo", "Memo")
                    .WithMany("Attachments")
                    .HasForeignKey("MemoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Memo");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("CorporateMemo.Domain.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("CorporateMemo.Domain.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("CorporateMemo.Domain.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("CorporateMemo.Domain.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CorporateMemo.Domain.Entities.Memo", b =>
            {
                b.Navigation("ApprovalSteps");
                b.Navigation("Attachments");
            });
#pragma warning restore 612, 618
        }
    }
}
